enable:
  issues: false
  prs: true

labels:
  'search':
    include:
      - 'search'
  'modetour':
    include:
      - 'modetour'
  'all':
    include:
      - 'all'
  'worldin':
    include:
      - 'worldin'
  'hotelin':
    include:
      - 'hotelin'
