enable:
  issues: false
  prs: true

labels:
  '검색':
    include:
      - '검색'
  '모두투어':
    include:
      - '모두투어'
  'search':
    include:
      - 'search'
  'modetour':
    include:
      - 'modetour'
  'all':
    include:
      - 'all'
  'worldin':
    include:
      - 'worldin'
  'hotelin':
    include:
      - 'hotelin'
