name: 'Label Actions'

on:
  pull_request:
    types: [labeled, unlabeled]

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/label-actions
        with:
          github-token: ${{ github.token }}
          process-only: 'prs'